language: java
jdk:
  - oraclejdk8
env:
  global:
    - GOOGLE_APPLICATION_CREDENTIALS=$TRAVIS_BUILD_DIR/travis/admin.json
    - GOOGLE_CLOUD_PROJECT=spring-cloud-gcp-ci
branches:
  only:
    - master
    - 1.0.x
    - test
cache:
  directories:
    - $HOME/google-cloud-sdk
    - $HOME/.m2
script:
  - ./mvnw -T 1.5C test -B ${INTEGRATION_TEST_FLAGS}
install:
  - ./mvnw -T 1.5C install -P it -DskipTests=true -Dmaven.javadoc.skip=true -B -V
before_install:
  - INTEGRATION_TEST_FLAGS="-Dit.logging=true";
      if [ "$TRAVIS_SECURE_ENV_VARS" == "true" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
        openssl aes-256-cbc -K $encrypted_1ef8dfbdb114_key -iv $encrypted_1ef8dfbdb114_iv -in travis.tar.gz.enc -out travis.tar.gz -d;
        tar -xzf travis.tar.gz;
      fi;
      export INTEGRATION_TEST_FLAGS;
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update --quiet
  - gcloud components install beta pubsub-emulator --quiet
  - gcloud config set project spring-cloud-gcp-ci
